QueueManager:
  class: Pantono\Queue\QueueManager
QueueFactory:
  class: Pantono\Queue\Factory\QueueFactory
  parameters:
    - "@QueueConnection"
QueueConnection:
  class: Pantono\Queue\Factory\DsnQueueFactory
