QueueManager:
  class: Pantono\Queue\QueueManager
QueueFactory:
  class: Pantono\Queue\Factory\QueueFactory
DsnQueueFactory:
  class: Pantono\Queue\Factory\DsnQueueFactory
  alias: Interop\Queue\ConnectionFactory
QueueConnection:
  class: Pantono\Queue\Factory\DsnQueueFactory
  parameters:
    - $queue.dsn
